Vagrant.configure("2") do |config|
  config.nfs.functional = false
  config.vm.box = "debian11"
  config.vm.box_version = "11.6.0-20230419.0"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
