# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.nfs.functional = false
  config.vm.box = "alma9"
  config.vm.box_version = "9.3-20231214.0"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
